{ pkgs, lib, config, customConfigs, quickshell-pkg, ... }:
let
  cfg = customConfigs.softwareConfigs.modules.quickshell;

  ## Pull styling from the same presets the rest of the shell uses, so Quickshell
  ## renders with the machine's active fonts and theme flavor rather than hardcoded
  ## values.
  fonts = customConfigs.styleConfigs.fonts.apply { inherit pkgs; };
  theme = customConfigs.styleConfigs.themes.apply { inherit pkgs; };

  ## Monitor + workspace layout come from the same presets Hyprland/Waybar use,
  ## so the shell draws the machine's real per-monitor workspace binding.
  monitors   = customConfigs.hardwareConfigs.monitors.apply { inherit pkgs; };
  workspaces = customConfigs.styleConfigs.workspaces.apply { inherit pkgs monitors; };

  ## Catppuccin palettes keyed by flavor. Only flavors selectable by a theme preset
  ## need to exist here. Hex values match the ones used in the Waybar style.css asset
  ## so Quickshell and Waybar stay visually identical during the coexistence phase.
  palettes = {
    macchiato = {
      rosewater = "#f4dbd6"; flamingo = "#f0c6c6"; pink     = "#f5bde6";
      mauve     = "#c6a0f6"; red      = "#ed8796"; maroon   = "#ee99a0";
      peach     = "#f5a97f"; yellow   = "#eed49f"; green    = "#a6da95";
      teal      = "#8bd5ca"; sky      = "#91d7e3"; sapphire = "#7dc4e4";
      blue      = "#8aadf4"; lavender = "#b7bdf8";
      text      = "#cad3f5"; subtext1 = "#b8c0e0"; subtext0 = "#a5adcb";
      overlay2  = "#939ab7"; overlay1 = "#8087a2"; overlay0 = "#6e738d";
      surface2  = "#5b6078"; surface1 = "#494d64"; surface0 = "#363a4f";
      base      = "#24273a"; mantle   = "#1e2030"; crust    = "#181926";
    };
  };

  palette = palettes.${theme.flavor}
    or (throw "quickshell: no Catppuccin palette defined for theme flavor '${theme.flavor}'");

  ## Emit one `readonly property color <name>: "<hex>"` line per palette entry.
  paletteProps = lib.concatStringsSep "\n" (
    lib.mapAttrsToList
      (name: hex: "    readonly property color ${name}: \"${hex}\"")
      palette
  );

  ## Generated Theme singleton. Every Quickshell component reads colors/fonts/metrics
  ## from here. Regenerated on rebuild — do not edit the file in ~/.config directly.
  themeQml = ''
    pragma Singleton
    import Quickshell
    import QtQuick

    // GENERATED by homeManagerModules/quickshell/home.nix from the active theme +
    // fonts presets. Do not edit by hand.
    Singleton {
        // ---- Catppuccin ${theme.flavor} palette ----
    ${paletteProps}

        // ---- Semantic aliases ----
        // Screen Bars direction: solid Crust bars with filled, dark-on-accent pills.
        readonly property color bg:         crust     // bar background (solid)
        readonly property color surface:    surface0  // neutral pill (clock, occupied ws)
        readonly property color surfaceAlt: surface1
        readonly property color fg:         text
        readonly property color accent:     mauve     // primary accent (Screen Bars 1a)
        readonly property color onAccent:   crust     // text/icon on a filled accent pill
        readonly property color border:     "#2a2b3d" // hairline under the bar

        // Workspace pill states
        readonly property color wsContainer: mantle    // workspace strip background
        readonly property color wsActive:    lavender  // active workspace on this monitor
        readonly property color wsOccupied:  surface0  // occupied but not active
        readonly property color wsIdleFg:    overlay0  // empty workspace glyph

        // ---- Typography (from the active fonts preset) ----
        readonly property string fontUi:   "${fonts.sansSerif.exact-name}"
        readonly property string fontMono: "${fonts.mono.exact-name}"

        // ---- Localisation ----
        // Date/time strings render in this locale (the host sets LC_TIME=fr_FR),
        // rather than Qt's default from LANG (en_US). Change here to switch language.
        readonly property string locale: "fr_FR"

        // ---- Metrics ----
        // The Screen Bars mockup is drawn at ~0.573x (1972px depicting a 3440px
        // monitor), so its literal px are scaled up ~1.75x here to match the design's
        // real proportions. Tune `barHeight` and the rest follow the same ratios.
        readonly property int barHeight:   46
        readonly property int pillHeight:  38   // clock / system-module pills
        readonly property int pillRadius:  7
        readonly property int wsHeight:    36   // workspace strip + pills
        readonly property int wsRadius:    8
        readonly property int fontNormal:  17   // main pill text (px)
        readonly property int fontIcon:    19   // Nerd Font glyph size (px)
    }
  '';

  ## Per-monitor workspace layout, projected from the workspaces preset into a QML
  ## data singleton. The Screen Bars pills read { id, icon, monitor } from here (the
  ## repo's Nerd Font glyphs + monitor binding); live focus/occupancy comes from
  ## Hyprland at runtime. Regenerated on rebuild — do not edit in ~/.config.
  wsEntries = lib.concatMapStringsSep ",\n" (w:
    "            { \"id\": ${toString w.id}, \"icon\": \"${w.icon}\", \"monitor\": \"${w.monitor}\" }"
  ) workspaces.workspaces_defined;

  ## Monitor-name → role map (from the disposition) so each Bar can select its
  ## modules by role. The content routing lives in Bar.qml; this is just the data.
  roleEntries = ''"${monitors.disposition.code}": "code", "${monitors.disposition.terminal}": "terminal", "${monitors.disposition.browser}": "browser"'';

  ## Per-screen bar layout (Screen Bars · Filled). Data-driven composition keyed by
  ## monitor role: each zone (left/center/right) is a list of entries, each either a
  ## real widget ({ w = "clock"; }) or a design stub ({ w = "stub"; icon; label;
  ## color; }). `icon` is a Nerd Font codepoint (hex, no backslash); `color` is a
  ## Theme palette name. Override the whole map per host via
  ## softwareConfigs.modules.quickshell.bars. Stubs mirror the mockup until each is
  ## replaced by a real widget (add a case in qml/widgets/WidgetSlot.qml).
  defaultBarsLayout = {
    browser = {                                            # ultrawide hub — global modules
      left = [
        { w = "clock"; }
        { w = "stub"; icon = "f1f6"; color = "mauve"; }                    # DND (bell-slash)
        { w = "stub"; icon = "f111"; label = "REC"; color = "red"; }      # recording
        { w = "stub"; icon = "f11c"; label = "resize"; color = "peach"; } # submap
        { w = "stub"; icon = "f0f4"; color = "teal"; }                    # idle inhibitor
      ];
      center = [ { w = "workspaces"; } ];
      right = [
        { w = "system"; }
        { w = "stub"; icon = "f11b"; color = "green"; }                   # GameMode
        { w = "stub"; icon = "f1de"; label = "scx·rusty"; color = "sky"; }
        { w = "volume"; }
        { w = "stub"; icon = "f0f3"; label = "3"; color = "rosewater"; }  # notifications
      ];
    };
    code = {                                               # left screen — primary
      left = [
        { w = "avatar"; }
        { w = "stub"; icon = "f015"; color = "blue"; }   # Home
        { w = "stub"; icon = "f019"; color = "teal"; }   # Downloads
      ];
      center = [ { w = "workspaces"; } ];
      right = [
        { w = "stub"; icon = "f11c"; label = "resize"; color = "peach"; }
        { w = "stub"; icon = "f2c9"; label = "34% · 78°"; color = "peach"; }  # cpu/temp
        { w = "volume"; }
      ];
    };
    terminal = {                                           # right screen — minimal
      left = [
        { w = "clock"; compact = true; }
        { w = "stub"; icon = "f11c"; label = "resize"; color = "peach"; }
      ];
      center = [ { w = "workspaces"; } ];
      right = [
        { w = "stub"; icon = "f108"; label = "LLM my face"; color = "red"; dashed = true; }
        { w = "stub"; icon = "f062"; label = "1.2M"; color = "sky"; }
        { w = "stub"; icon = "f063"; label = "8.4M"; color = "green"; }
      ];
    };
    other = {                                              # any unmapped monitor
      left = [ { w = "clock"; compact = true; } ];
      center = [ { w = "workspaces"; } ];
      right = [ { w = "system"; } { w = "volume"; } ];
    };
  };

  barsLayout = if (cfg ? bars && cfg.bars != {}) then cfg.bars else defaultBarsLayout;

  ## Render the layout attrset into a QML object literal. `\u<hex>` is emitted for
  ## the glyph so QML interprets the escape at runtime — the backslash survives
  ## because Config.qml is generated inside a '' string (no C-escape processing).
  escStr = lib.escape [ "\"" "\\" ];
  renderEntry = e:
    let
      parts =
        [ ''"w": "${e.w}"'' ]
        ++ lib.optional (e ? icon)    ''"icon": "\u${e.icon}"''
        ++ lib.optional (e ? label)   ''"label": "${escStr e.label}"''
        ++ lib.optional (e ? color)   ''"color": "${e.color}"''
        ++ lib.optional (e ? compact) ''"compact": ${lib.boolToString e.compact}''
        ++ lib.optional (e ? dashed)  ''"dashed": ${lib.boolToString e.dashed}'';
    in "{ ${lib.concatStringsSep ", " parts} }";
  renderZone = z: "[ ${lib.concatMapStringsSep ", " renderEntry z} ]";
  renderRole = name: r:
    ''"${name}": { "left": ${renderZone r.left}, "center": ${renderZone r.center}, "right": ${renderZone r.right} }'';
  barLayoutQml =
    "({ ${lib.concatStringsSep ", " (lib.mapAttrsToList renderRole barsLayout)} })";

  configQml = ''
    pragma Singleton
    import Quickshell
    import QtQuick

    // GENERATED by homeManagerModules/quickshell/home.nix from the workspaces +
    // monitors presets. Do not edit by hand.
    Singleton {
        // Per-monitor workspace layout: id · Nerd Font glyph · target monitor.
        readonly property var workspaces: [
    ${wsEntries}
        ]

        // Monitor connector name → role ("code" | "terminal" | "browser"), so each
        // Bar can compose modules for its screen. (Parenthesised so QML reads it as
        // an object literal, not a statement block.)
        readonly property var roles: ({ ${roleEntries} })

        // The ultrawide "hub" monitor — carries global modules in later stages.
        readonly property string hubMonitor: "${monitors.disposition.browser}"

        // Per-screen bar composition, keyed by role. Each zone lists widget entries
        // dispatched by qml/widgets/WidgetSlot.qml. Generated from the barsLayout
        // preset in home.nix. (Parenthesised so QML reads it as an object literal.)
        readonly property var barLayout: ${barLayoutQml}

        // Profile photo for the avatar widget (installed alongside the QML tree).
        readonly property string profileImage: "file://${config.xdg.configHome}/quickshell/assets/profile.jpg"
    }
  '';
in
{
  config = lib.mkIf cfg.enable {
    ## Install the Quickshell binary (upstream flake build, passed in via
    ## extraSpecialArgs as quickshell-pkg). Launch manually with `qs` for now —
    ## no autostart while it coexists with Waybar.
    home.packages = [ quickshell-pkg ];

    xdg.configFile = {
      "quickshell/Theme.qml".text     = themeQml;
      "quickshell/Config.qml".text    = configQml;
      "quickshell/Popovers.qml".source = ./qml/Popovers.qml;
      "quickshell/shell.qml".source   = ./qml/shell.qml;
      "quickshell/Bar.qml".source   = ./qml/Bar.qml;
      "quickshell/widgets".source   = ./qml/widgets;
      "quickshell/scripts".source   = ./scripts;
      "quickshell/assets/profile.jpg".source =
        ../../configurations/style/status-bars/assets/profile_oneill.jpg;
    };
  };
}
