{ pkgs, lib, config, customConfigs, quickshell-pkg, ... }:
let
  cfg = customConfigs.softwareConfigs.modules.quickshell;

  ## Pull styling from the same presets the rest of the shell uses, so Quickshell
  ## renders with the machine's active fonts and theme flavor rather than hardcoded
  ## values.
  fonts = customConfigs.styleConfigs.fonts.apply { inherit pkgs; };
  theme = customConfigs.styleConfigs.themes.apply { inherit pkgs; };

  ## Catppuccin palettes keyed by flavor. Only flavors selectable by a theme preset
  ## need to exist here. Hex values match the ones used in the Waybar style.css asset
  ## so Quickshell and Waybar stay visually identical during the coexistence phase.
  palettes = {
    macchiato = {
      rosewater = "#f4dbd6"; flamingo = "#f0c6c6"; pink     = "#f5bde6";
      mauve     = "#c6a0f6"; red      = "#ed8796"; maroon   = "#ee99a0";
      peach     = "#f5a97f"; yellow   = "#eed49f"; green    = "#a6da95";
      teal      = "#8bd5ca"; sky      = "#91d7e3"; sapphire = "#7dc4e4";
      blue      = "#8aadf4"; lavender = "#b7bdf8";
      text      = "#cad3f5"; subtext1 = "#b8c0e0"; subtext0 = "#a5adcb";
      overlay2  = "#939ab7"; overlay1 = "#8087a2"; overlay0 = "#6e738d";
      surface2  = "#5b6078"; surface1 = "#494d64"; surface0 = "#363a4f";
      base      = "#24273a"; mantle   = "#1e2030"; crust    = "#181926";
    };
  };

  palette = palettes.${theme.flavor}
    or (throw "quickshell: no Catppuccin palette defined for theme flavor '${theme.flavor}'");

  ## Emit one `readonly property color <name>: "<hex>"` line per palette entry.
  paletteProps = lib.concatStringsSep "\n" (
    lib.mapAttrsToList
      (name: hex: "    readonly property color ${name}: \"${hex}\"")
      palette
  );

  ## Generated Theme singleton. Every Quickshell component reads colors/fonts/metrics
  ## from here. Regenerated on rebuild — do not edit the file in ~/.config directly.
  themeQml = ''
    //@ pragma Singleton
    import Quickshell
    import QtQuick

    // GENERATED by homeManagerModules/quickshell/home.nix from the active theme +
    // fonts presets. Do not edit by hand.
    Singleton {
        // ---- Catppuccin ${theme.flavor} palette ----
    ${paletteProps}

        // ---- Semantic aliases ----
        readonly property color bg:         base
        readonly property color surface:    surface0
        readonly property color surfaceAlt: surface1
        readonly property color fg:         text
        readonly property color accent:     blue

        // ---- Typography (from the active fonts preset) ----
        readonly property string fontUi:   "${fonts.sansSerif.exact-name}"
        readonly property string fontMono: "${fonts.mono.exact-name}"

        // ---- Metrics ----
        readonly property int barHeight: 40
    }
  '';
in
{
  config = lib.mkIf cfg.enable {
    ## Install the Quickshell binary (upstream flake build, passed in via
    ## extraSpecialArgs as quickshell-pkg). Launch manually with `qs` for now —
    ## no autostart while it coexists with Waybar.
    home.packages = [ quickshell-pkg ];

    xdg.configFile = {
      "quickshell/Theme.qml".text   = themeQml;
      "quickshell/shell.qml".source = ./qml/shell.qml;
    };
  };
}
