{ pkgs, lib, config, customConfigs, quickshell-pkg, ... }:
let
  cfg = customConfigs.softwareConfigs.modules.quickshell;

  ## Pull styling from the same presets the rest of the shell uses, so Quickshell
  ## renders with the machine's active fonts and theme flavor rather than hardcoded
  ## values.
  fonts = customConfigs.styleConfigs.fonts.apply { inherit pkgs; };
  theme = customConfigs.styleConfigs.themes.apply { inherit pkgs; };

  ## Monitor + workspace layout come from the same presets Hyprland/Waybar use,
  ## so the shell draws the machine's real per-monitor workspace binding.
  monitors   = customConfigs.hardwareConfigs.monitors.apply { inherit pkgs; };
  workspaces = customConfigs.styleConfigs.workspaces.apply { inherit pkgs monitors; };

  ## Catppuccin palettes keyed by flavor. Only flavors selectable by a theme preset
  ## need to exist here. Hex values match the ones used in the Waybar style.css asset
  ## so Quickshell and Waybar stay visually identical during the coexistence phase.
  palettes = {
    macchiato = {
      rosewater = "#f4dbd6"; flamingo = "#f0c6c6"; pink     = "#f5bde6";
      mauve     = "#c6a0f6"; red      = "#ed8796"; maroon   = "#ee99a0";
      peach     = "#f5a97f"; yellow   = "#eed49f"; green    = "#a6da95";
      teal      = "#8bd5ca"; sky      = "#91d7e3"; sapphire = "#7dc4e4";
      blue      = "#8aadf4"; lavender = "#b7bdf8";
      text      = "#cad3f5"; subtext1 = "#b8c0e0"; subtext0 = "#a5adcb";
      overlay2  = "#939ab7"; overlay1 = "#8087a2"; overlay0 = "#6e738d";
      surface2  = "#5b6078"; surface1 = "#494d64"; surface0 = "#363a4f";
      base      = "#24273a"; mantle   = "#1e2030"; crust    = "#181926";
    };
  };

  palette = palettes.${theme.flavor}
    or (throw "quickshell: no Catppuccin palette defined for theme flavor '${theme.flavor}'");

  ## Emit one `readonly property color <name>: "<hex>"` line per palette entry.
  paletteProps = lib.concatStringsSep "\n" (
    lib.mapAttrsToList
      (name: hex: "    readonly property color ${name}: \"${hex}\"")
      palette
  );

  ## Generated Theme singleton. Every Quickshell component reads colors/fonts/metrics
  ## from here. Regenerated on rebuild — do not edit the file in ~/.config directly.
  themeQml = ''
    pragma Singleton
    import Quickshell
    import QtQuick

    // GENERATED by homeManagerModules/quickshell/home.nix from the active theme +
    // fonts presets. Do not edit by hand.
    Singleton {
        // ---- Catppuccin ${theme.flavor} palette ----
    ${paletteProps}

        // ---- Semantic aliases ----
        // Screen Bars direction: solid Crust bars with filled, dark-on-accent pills.
        readonly property color bg:         crust     // bar background (solid)
        readonly property color surface:    surface0  // neutral pill (clock, occupied ws)
        readonly property color surfaceAlt: surface1
        readonly property color fg:         text
        readonly property color accent:     mauve     // primary accent (Screen Bars 1a)
        readonly property color onAccent:   crust     // text/icon on a filled accent pill
        readonly property color border:     "#2a2b3d" // hairline under the bar

        // Workspace pill states
        readonly property color wsContainer: mantle    // workspace strip background
        readonly property color wsActive:    lavender  // active workspace on this monitor
        readonly property color wsOccupied:  surface0  // occupied but not active
        readonly property color wsIdleFg:    overlay0  // empty workspace glyph

        // ---- Typography (from the active fonts preset) ----
        readonly property string fontUi:   "${fonts.sansSerif.exact-name}"
        readonly property string fontMono: "${fonts.mono.exact-name}"

        // ---- Localisation ----
        // Date/time strings render in this locale (the host sets LC_TIME=fr_FR),
        // rather than Qt's default from LANG (en_US). Change here to switch language.
        readonly property string locale: "fr_FR"

        // ---- Metrics ----
        // The Screen Bars mockup is drawn at ~0.573x (1972px depicting a 3440px
        // monitor), so its literal px are scaled up ~1.75x here to match the design's
        // real proportions. Tune `barHeight` and the rest follow the same ratios.
        readonly property int barHeight:   46
        readonly property int pillHeight:  38   // clock / system-module pills
        readonly property int pillRadius:  7
        readonly property int wsHeight:    36   // workspace strip + pills
        readonly property int wsRadius:    8
        readonly property int fontNormal:  17   // main pill text (px)
        readonly property int fontIcon:    19   // Nerd Font glyph size (px)
    }
  '';

  ## Per-monitor workspace layout, projected from the workspaces preset into a QML
  ## data singleton. The Screen Bars pills read { id, icon, monitor } from here (the
  ## repo's Nerd Font glyphs + monitor binding); live focus/occupancy comes from
  ## Hyprland at runtime. Regenerated on rebuild — do not edit in ~/.config.
  wsEntries = lib.concatMapStringsSep ",\n" (w:
    "            { \"id\": ${toString w.id}, \"icon\": \"${w.icon}\", \"monitor\": \"${w.monitor}\" }"
  ) workspaces.workspaces_defined;

  ## Monitor-name → role map (from the disposition) so each Bar can select its
  ## modules by role. The content routing lives in Bar.qml; this is just the data.
  roleEntries = ''"${monitors.disposition.code}": "code", "${monitors.disposition.terminal}": "terminal", "${monitors.disposition.browser}": "browser"'';

  configQml = ''
    pragma Singleton
    import Quickshell
    import QtQuick

    // GENERATED by homeManagerModules/quickshell/home.nix from the workspaces +
    // monitors presets. Do not edit by hand.
    Singleton {
        // Per-monitor workspace layout: id · Nerd Font glyph · target monitor.
        readonly property var workspaces: [
    ${wsEntries}
        ]

        // Monitor connector name → role ("code" | "terminal" | "browser"), so each
        // Bar can compose modules for its screen. (Parenthesised so QML reads it as
        // an object literal, not a statement block.)
        readonly property var roles: ({ ${roleEntries} })

        // The ultrawide "hub" monitor — carries global modules in later stages.
        readonly property string hubMonitor: "${monitors.disposition.browser}"
    }
  '';
in
{
  config = lib.mkIf cfg.enable {
    ## Install the Quickshell binary (upstream flake build, passed in via
    ## extraSpecialArgs as quickshell-pkg). Launch manually with `qs` for now —
    ## no autostart while it coexists with Waybar.
    home.packages = [ quickshell-pkg ];

    xdg.configFile = {
      "quickshell/Theme.qml".text   = themeQml;
      "quickshell/Config.qml".text  = configQml;
      "quickshell/shell.qml".source = ./qml/shell.qml;
      "quickshell/Bar.qml".source   = ./qml/Bar.qml;
      "quickshell/widgets".source   = ./qml/widgets;
    };
  };
}
