## =======================================================================================
##  Shell :: generated Theme singleton
##
##  Both quickshell instances read this: the bar (homeManagerModules/quickshell) and
##  the notification server (homeManagerModules/quickshell-notify). One renderer here
##  is what keeps a toast the same colours as the bar it appears under — two copies of
##  the semantic aliases would drift the way the palette nearly did.
##
##  Config.qml is deliberately NOT here. The bar's carries its per-screen layout and
##  the notify instance's will carry the notification preset; they share colours and
##  fonts, nothing else. That split is also what lets the two units restart on
##  different triggers (docs/NOTIFICATIONS.md D1).
##
##  Usage:
##    let gen = import ../../qml/shell/generate.nix { inherit lib theme fonts; };
##    in gen.themeQml
## =======================================================================================
{ lib, theme, fonts }:

let
  pal     = import ../palette.nix { inherit lib; };
  palette = pal.forFlavor "quickshell" theme.flavor;

  ## Emit one `readonly property color <name>: "<hex>"` line per palette entry.
  paletteProps = pal.props palette;
in
{
  inherit palette;

  ## Generated Theme singleton. Every Quickshell component reads colors/fonts/metrics
  ## from here. Regenerated on rebuild — do not edit the file in ~/.config directly.
  themeQml = ''
    pragma Singleton
    import Quickshell
    import QtQuick

    // GENERATED by qml/shell/generate.nix from the active theme + fonts presets.
    // Do not edit by hand.
    Singleton {
        // ---- Catppuccin ${theme.flavor} palette ----
    ${paletteProps}

        // ---- Semantic aliases ----
        // Screen Bars direction: solid Crust bars with filled, dark-on-accent pills.
        readonly property color bg:         crust     // bar background (solid)
        readonly property color surface:    surface0  // neutral pill (clock, occupied ws)
        readonly property color surfaceAlt: surface1
        readonly property color fg:         text
        readonly property color accent:     mauve     // primary accent (Screen Bars 1a)
        readonly property color onAccent:   crust     // text/icon on a filled accent pill
        readonly property color border:     "#2a2b3d" // hairline under the bar

        // Workspace pill states
        readonly property color wsContainer: mantle    // workspace strip background
        readonly property color wsActive:    lavender  // active workspace on this monitor
        readonly property color wsOccupied:  surface0  // occupied but not active
        readonly property color wsIdleFg:    overlay0  // empty workspace glyph

        // ---- Typography (from the active fonts preset) ----
        readonly property string fontUi:   "${fonts.sansSerif.exact-name}"
        readonly property string fontMono: "${fonts.mono.exact-name}"

        // ---- Localisation ----
        // Date/time strings render in this locale (the host sets LC_TIME=fr_FR),
        // rather than Qt's default from LANG (en_US). Change here to switch language.
        readonly property string locale: "fr_FR"

        // ---- Metrics ----
        // The Screen Bars mockup is drawn at ~0.573x (1972px depicting a 3440px
        // monitor), so its literal px are scaled up ~1.75x here to match the design's
        // real proportions. Tune `barHeight` and the rest follow the same ratios.
        readonly property int barHeight:   46
        readonly property int pillHeight:  38   // clock / system-module pills
        readonly property int pillRadius:  7
        readonly property int wsHeight:    36   // workspace strip + pills
        readonly property int wsRadius:    8

        // Popovers (the bar's drop-downs): the gap that floats a panel clear of the
        // bar, the arrow notch pointing back at the chip, and the panel's corners.
        readonly property int popoverGap:    10
        readonly property int popoverArrowW: 18
        readonly property int popoverArrowH: 9
        readonly property int popoverRadius: 16

        readonly property int fontNormal:  17   // main pill text (px)
        readonly property int fontIcon:    19   // Nerd Font glyph size (px)
    }
  '';
}
