{ config, lib, pkgs, customConfigs, ... }:

let
  cfg = config.software.modules.sddm;

  ## Presentation comes from the same presets the rest of the desktop uses, so the
  ## greeter renders in the machine's active theme flavor and fonts rather than
  ## hardcoded values. Same sourcing as homeManagerModules/quickshell/home.nix.
  sddmStyle = customConfigs.styleConfigs.sddm.apply { inherit pkgs; };
  theme     = customConfigs.styleConfigs.themes.apply { inherit pkgs; };
  fonts     = customConfigs.styleConfigs.fonts.apply { inherit pkgs; };
  monitors  = customConfigs.hardwareConfigs.monitors.apply { inherit pkgs; };

  ## Catppuccin palettes keyed by flavor, identical to the table the quickshell
  ## module renders into its Theme.qml — the greeter and the shell it hands over
  ## to must agree on every hex value, so they are kept literally the same.
  palettes = {
    macchiato = {
      rosewater = "#f4dbd6"; flamingo = "#f0c6c6"; pink     = "#f5bde6";
      mauve     = "#c6a0f6"; red      = "#ed8796"; maroon   = "#ee99a0";
      peach     = "#f5a97f"; yellow   = "#eed49f"; green    = "#a6da95";
      teal      = "#8bd5ca"; sky      = "#91d7e3"; sapphire = "#7dc4e4";
      blue      = "#8aadf4"; lavender = "#b7bdf8";
      text      = "#cad3f5"; subtext1 = "#b8c0e0"; subtext0 = "#a5adcb";
      overlay2  = "#939ab7"; overlay1 = "#8087a2"; overlay0 = "#6e738d";
      surface2  = "#5b6078"; surface1 = "#494d64"; surface0 = "#363a4f";
      base      = "#24273a"; mantle   = "#1e2030"; crust    = "#181926";
    };
  };

  palette = palettes.${theme.flavor}
    or (throw "sddm-stargate: no Catppuccin palette defined for theme flavor '${theme.flavor}'");

  paletteProps = lib.concatStringsSep "\n" (
    lib.mapAttrsToList
      (name: hex: "    readonly property color ${name}: \"${hex}\"")
      palette
  );

  ## Render an attrset of Nix scalars as a QML object literal. Parenthesised so
  ## QML reads it as an object, not a statement block.
  scalarObject = attrs: "({ " + lib.concatStringsSep ", " (lib.mapAttrsToList (n: v:
    ''"${n}": '' + (
      if builtins.isString v then ''"${v}"''
      else if builtins.isBool v then lib.boolToString v
      else toString v
    )
  ) attrs) + " })";

  ## Same, for Nerd Font codepoints. The backslash survives because the caller
  ## builds its file inside a '' string, so QML — not Nix — reads the \uXXXX.
  glyphObject = attrs: "({ " + lib.concatStringsSep ", " (lib.mapAttrsToList (n: v:
    ''"${n}": "\u${v}"''
  ) attrs) + " })";

  ## ---- Generated singletons -------------------------------------------------
  ## Both land in the theme's Config/ directory, which carries a qmldir declaring
  ## them as singletons. Regenerated on every rebuild — never edit the installed
  ## copies under /run/current-system.

  themeQml = ''
    pragma Singleton
    import QtQuick

    // GENERATED by nixosModules/sddm-stargate/default.nix from the active theme +
    // fonts presets. Do not edit by hand.
    QtObject {
        // ---- Catppuccin ${theme.flavor} palette ----
    ${paletteProps}

        // ---- Semantic aliases ----
        readonly property color bg:       crust     // screen background
        readonly property color panel:    mantle    // bar, cards, segmented controls
        readonly property color border:   surface0  // panel outlines, dividers
        readonly property color hairline: base      // list row separators
        readonly property color fg:       text
        readonly property color dim:      overlay0  // secondary labels
        readonly property color label:    overlay1  // section kickers
        readonly property color onAccent: crust     // text on a filled accent

        // A chevron that has not engaged. Between base and surface0, dark enough
        // that an unlit chevron reads as off rather than merely dimmer.
        readonly property color unlit: "#2a2b3d"

        // ---- Typography (from the active fonts preset) ----
        readonly property string fontUi:   "${fonts.sansSerif.exact-name}"
        readonly property string fontMono: "${fonts.mono.exact-name}"

        // ---- Localisation ----
        // Named explicitly: the greeter runs as the `sddm` user and inherits
        // neither the host's LANG nor its LC_TIME.
        readonly property string locale: "${sddmStyle.locale}"

        // ---- Metrics ----
        // Every screen is authored in a 1080px-tall design space and scaled to
        // the monitor's real height, so these are design pixels.
        readonly property int designHeight: 1080
        readonly property int barHeight:    52
        readonly property int barMargin:    18
        readonly property int barRadius:    16
    }
  '';

  configQml = ''
    pragma Singleton
    import QtQuick

    // GENERATED by nixosModules/sddm-stargate/default.nix from the sddm style
    // preset. Do not edit by hand.
    QtObject {
        // Connector name -> screen role. SDDM builds one QML engine per monitor,
        // so each view reads this to decide which of the three screens it is.
        readonly property var screens: ${scalarObject sddmStyle.screens}

        // Theme palette *names*, resolved as Theme[name] at the use site so a
        // theme flavor change follows without regenerating this file.
        readonly property var colors: ${scalarObject sddmStyle.colors}

        // Gate geometry and dialling behaviour. maxPreLock bounds how many
        // chevrons typing may light before Enter, and therefore how much of the
        // password's length the screen reveals.
        readonly property var gate: ${scalarObject sddmStyle.gate}

        // Dial-home device: two rings of `keys`, reshuffling its lit set every
        // `shimmerMs`.
        readonly property var dhd: ${scalarObject sddmStyle.dhd}

        readonly property bool clock24: ${lib.boolToString sddmStyle.clock24}

        // Chrome glyphs, as Nerd Font codepoints.
        readonly property var icons: ${glyphObject sddmStyle.icons}

        // Session name (lowercased) -> glyph for the "Destination" picker.
        readonly property var sessionIcons: ${glyphObject sddmStyle.sessionIcons}
    }
  '';

  metadataDesktop = ''
    [SddmGreeterTheme]
    Name=Stargate
    Description=SGC gate room — dial in to log in
    Type=sddm-theme
    Version=1.0
    License=MIT
    Theme-Id=stargate
    Theme-API=2.0
    MainScript=Main.qml
    ConfigFile=theme.conf
  '';

  ## Only the knobs worth changing without a rebuild live here. SDDM also reads
  ## theme.conf.user, so a writable copy of the theme can be driven through every
  ## state under `sddm-greeter-qt6 --test-mode`.
  themeConf = ''
    [General]
    # auto | gate | dhd | telemetry — force a screen regardless of the connector
    previewScreen=auto
    # live | dialing | error | capslock | success — force a gate state
    previewState=live
  '';

  themePackage = pkgs.runCommand "sddm-stargate-theme"
    {
      meta = {
        description = "SDDM greeter theme: the SGC gate room across three monitors";
        platforms   = lib.platforms.linux;
      };
    }
    ''
      dir=$out/share/sddm/themes/stargate
      mkdir -p "$dir"
      cp -r ${./theme}/. "$dir/"
      chmod -R u+w "$dir"

      cp ${pkgs.writeText "Theme.qml" themeQml}               "$dir/Config/Theme.qml"
      cp ${pkgs.writeText "Config.qml" configQml}             "$dir/Config/Config.qml"
      cp ${pkgs.writeText "metadata.desktop" metadataDesktop} "$dir/metadata.desktop"
      cp ${pkgs.writeText "theme.conf" themeConf}             "$dir/theme.conf"
    '';

  ## Typo guard: a connector named in the preset that the monitors preset does not
  ## know about will never match a screen. Warn rather than fail — the greeter
  ## still comes up, and a host may legitimately run with a monitor unplugged.
  knownMonitors  = map (m: m.name) monitors.definition;
  unknownScreens = lib.filter (n: !(lib.elem n knownMonitors))
    (lib.attrValues sddmStyle.screens);
in
{
  options.software.modules.sddm = {
    enable = lib.mkOption {
      type    = lib.types.bool;
      default = false;
      description = ''
        Install and select the Stargate SDDM greeter theme. Requires
        services.displayManager.sddm.enable — this module only supplies the
        theme, it does not turn the display manager on.
      '';
    };

    package = lib.mkOption {
      type    = lib.types.package;
      default = themePackage;
      defaultText = lib.literalExpression "the theme built from ./theme and the active presets";
      description = ''
        The built theme. Exposed so it can be previewed without a rebuild:

          sddm-greeter-qt6 --test-mode --theme \
            "$(nix build --no-link --print-out-paths \
               .#nixosConfigurations.<host>.config.software.modules.sddm.package)/share/sddm/themes/stargate"
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    warnings = lib.optional (unknownScreens != [ ]) ''
      sddm-stargate: the sddm style preset assigns screens to connectors the active
      monitors preset does not define: ${lib.concatStringsSep ", " unknownScreens}.
      Those screens will never be drawn; the gate falls back to the widest monitor.
    '';

    environment.systemPackages = [ cfg.package ];

    ## SDDM resolves Theme.Current against /run/current-system/sw/share/sddm/themes,
    ## so the theme *name* — not a store path — is what belongs here.
    services.displayManager.sddm.theme = "stargate";

    ## The greeter runs as the `sddm` user, outside the Home Manager profile, so it
    ## only sees fonts installed system-wide. Stylix already installs these from the
    ## same preset; listing them makes the greeter independent of that.
    fonts.packages = [
      fonts.mono.package
      fonts.sansSerif.package
    ];
  };
}
