{ pkgs, lib, config, customConfigs, quickshell-pkg, ... }:

let
  cfg = customConfigs.softwareConfigs.modules.quickshell-notify;

  configDir = "$HOME/.config/quickshell-notify";

  fonts = customConfigs.styleConfigs.fonts.apply { inherit pkgs; };
  theme = customConfigs.styleConfigs.themes.apply { inherit pkgs; };

  ## The same Theme the bar renders, from the same generator — a toast must not be a
  ## different shade of mantle than the bar it appears under. Config.qml is
  ## deliberately not shared: the bar's carries its per-screen layout, and this
  ## instance will carry the notification preset (docs/NOTIFICATIONS.md D1).
  shellTheme = import ../../qml/shell/generate.nix { inherit lib theme fonts; };

  ## Notification preset — placement, timing and the urgency colours. Comes from the
  ## same quickshell style preset the bar reads, so one file owns the whole shell's
  ## composition even though the two instances render different parts of it.
  default-programs = customConfigs.softwareConfigs.defaults.apply { inherit pkgs; };
  quickshellStyle  = customConfigs.styleConfigs.quickshell.apply { inherit pkgs default-programs; };
  n                = quickshellStyle.notifications;

  ## The preset names a monitor ROLE; resolve it to the connector here rather than
  ## shipping a roles table this instance would use exactly once.
  monitors   = customConfigs.hardwareConfigs.monitors.apply { inherit pkgs; };
  screenName = monitors.disposition.${n.monitor} or "";

  urgencyQml = lib.concatStringsSep ", " (lib.mapAttrsToList (level: v:
    ''"${level}": ({ "bg": "${v.bg}", "border": "${v.border}" })''
  ) n.urgency);

  configQml = ''
    pragma Singleton
    import Quickshell
    import QtQuick

    // GENERATED by homeManagerModules/quickshell-notify/home.nix from the quickshell
    // style preset. Do not edit by hand.
    Singleton {
        // Monitor ROLE the toast stack renders on, and the stack's geometry.
        // The preset names a role; this is the connector it resolved to.
        readonly property string monitor: "${n.monitor}"
        readonly property string screen:  "${screenName}"
        readonly property string accent:  "${n.accent}"
        readonly property int width:      ${toString n.width}
        readonly property int gap:        ${toString n.gap}
        readonly property int radius:     ${toString n.radius}
        readonly property int margin:     ${toString n.margin}

        // Cards on screen at once; anything beyond this waits its turn.
        readonly property int maxVisible: ${toString n.maxVisible}

        // Countdown for non-urgent cards. Urgent ones never expire (D8).
        readonly property int holdMs:     ${toString n.holdMs}
        readonly property int bodyLines:  ${toString n.bodyLines}

        // Per-level card fill + border, keyed by the lowercased urgency name.
        readonly property var urgency: ({ ${urgencyQml} })
    }
  '';

  ## xdg.configFile cannot mix a source directory with a generated file, so the tree
  ## is merged in the store first — the same shape quickshell-lock uses.
  notifyTree = pkgs.runCommand "quickshell-notify-qml" { } ''
    mkdir -p $out
    cp -r ${./qml}/. $out/
    chmod -R u+w $out   # store copies come in read-only, incl. the directories

    cp ${pkgs.writeText "Theme.qml" shellTheme.themeQml}   $out/Theme.qml
    cp ${pkgs.writeText "Config.qml" configQml}            $out/Config.qml
  '';

  ## Phase 1 runs on a throwaway session bus, where org.freedesktop.Notifications is
  ## unowned while WAYLAND_DISPLAY still reaches the real monitors — so the server
  ## under development never contends with the swaync that is serving real
  ## notifications (docs/NOTIFICATIONS.md D3). Scaffolding: both wrappers are deleted
  ## at the phase 8 flag day, along with the -dev paths they imply.
  devWrapper = pkgs.writeShellScriptBin "quickshell-notify-dev" ''
    exec ${pkgs.dbus}/bin/dbus-run-session -- \
      ${quickshell-pkg}/bin/quickshell -p "${configDir}"
  '';

  ## Runs any command against the dev instance's private session bus. The instance's
  ## bus address is only discoverable from its own environment, so this reads it back
  ## out of /proc — and every notification tool needs it, not just notify-send:
  ##
  ##   quickshell-notify-bus busctl --user call org.freedesktop.Notifications \
  ##     /org/freedesktop/Notifications org.freedesktop.Notifications CloseNotification u 3
  ##
  ## `-x` (match the WHOLE command line, not a substring) is load-bearing. A plain
  ## `pgrep -f` also matches the `dbus-run-session` parent, which carries this command
  ## as its *arguments*, and any shell whose command line merely mentions the path —
  ## both of which sit on the real bus.
  ##
  ## The pid is matched against the package's own store path, not `quickshell` on
  ## PATH: the dev wrapper execs the store binary, so a PATH lookup finds the profile
  ## symlink instead and matches nothing. That failure is silent and nasty — an empty
  ## address makes sd-bus fall back to the real session bus, so the command lands in
  ## swaync and looks like it worked. Hence the explicit guards below.
  busWrapper = pkgs.writeShellScriptBin "quickshell-notify-bus" ''
    set -eu

    if [ "$#" -eq 0 ]; then
      echo "usage: quickshell-notify-bus <command> [args...]" >&2
      echo "  runs <command> against the quickshell-notify dev instance's bus" >&2
      exit 2
    fi

    pid=$(${pkgs.procps}/bin/pgrep -f -x \
            "${quickshell-pkg}/bin/quickshell -p ${configDir}" | head -1 || true)

    if [ -z "''${pid:-}" ]; then
      echo "quickshell-notify-bus: no dev instance running." >&2
      echo "  start one first:  quickshell-notify-dev" >&2
      exit 1
    fi

    bus=$(tr '\0' '\n' < "/proc/$pid/environ" \
            | grep '^DBUS_SESSION_BUS_ADDRESS=' | cut -d= -f2- || true)

    if [ -z "''${bus:-}" ]; then
      echo "quickshell-notify-bus: pid $pid has no DBUS_SESSION_BUS_ADDRESS." >&2
      echo "  it was not started through quickshell-notify-dev." >&2
      exit 1
    fi

    if [ "$bus" = "''${DBUS_SESSION_BUS_ADDRESS:-}" ]; then
      echo "quickshell-notify-bus: refusing to run — the instance is on the REAL" >&2
      echo "  session bus, not a private one. That is swaync's bus." >&2
      exit 1
    fi

    exec env DBUS_SESSION_BUS_ADDRESS="$bus" "$@"
  '';

  ## Convenience for the common case. All the discovery lives in the bus wrapper.
  sendWrapper = pkgs.writeShellScriptBin "quickshell-notify-send" ''
    exec ${busWrapper}/bin/quickshell-notify-bus ${pkgs.libnotify}/bin/notify-send "$@"
  '';
in
{
  config = lib.mkIf cfg.enable {
    ## libnotify also lands on PATH so `notify-send` is available directly — it goes
    ## to the real bus, which is useful for checking swaync still works. Scoped to
    ## this module rather than the global package list: it exists for this work and
    ## leaves with it.
    home.packages = [ devWrapper busWrapper sendWrapper pkgs.libnotify ];

    xdg.configFile."quickshell-notify".source = notifyTree;

    ## No systemd.user.services block, on purpose. Enabling this module installs an
    ## inert config directory and four commands; nothing starts at login and nothing
    ## claims a bus name. The unit lands at phase 8, in the same rebuild that
    ## disables swaync — see docs/NOTIFICATIONS.md, Roadmap.
  };
}
