## =======================================================================================
##  Stargate :: generated QML singletons
##
##  Both consumers of the shared tree — the SDDM greeter (nixosModules/sddm-stargate)
##  and the lock screen (homeManagerModules/quickshell-lock) — render the same two
##  singletons from the same presets, so the gate looks identical whether the machine
##  is cold or merely idle. Keeping one renderer here is what guarantees that.
##
##  The palette itself lives in qml/palette.nix, shared with the bar and the
##  notification server (qml/shell/generate.nix) — it used to be a second copy of the
##  same table here, which is exactly the drift this file warns about.
##
##  Usage:
##    let gen = import ../../qml/stargate/generate.nix {
##                inherit lib; style = ...; theme = ...; fonts = ...;
##              };
##    in gen.themeQml  /  gen.configQml
##
##  The output lands in the tree's Config/ directory, next to the hand-written
##  MissionData.qml that Config/qmldir declares alongside them.
## =======================================================================================
{ lib, style, theme, fonts }:

let
  ## The palette is shared with the bar and the notification server — see
  ## qml/palette.nix. The greeter, the lock and the bar must agree on every colour,
  ## and one table is what guarantees it.
  pal     = import ../palette.nix { inherit lib; };
  palette = pal.forFlavor "stargate" theme.flavor;

  paletteProps = pal.props palette;

  ## Render an attrset of Nix scalars as a QML object literal. Parenthesised so QML
  ## reads it as an object, not a statement block.
  scalarObject = attrs: "({ " + lib.concatStringsSep ", " (lib.mapAttrsToList (n: v:
    ''"${n}": '' + (
      if builtins.isString v then ''"${v}"''
      else if builtins.isBool v then lib.boolToString v
      else if builtins.isList v then "[ " + lib.concatMapStringsSep ", " (x: ''"${x}"'') v + " ]"
      else toString v
    )
  ) attrs) + " })";

  ## Same, for Nerd Font codepoints. The backslash survives because this is built
  ## inside a '' string, so QML — not Nix — reads the \uXXXX.
  glyphObject = attrs: "({ " + lib.concatStringsSep ", " (lib.mapAttrsToList (n: v:
    ''"${n}": "\u${v}"''
  ) attrs) + " })";
in
{
  inherit palette;

  themeQml = ''
    pragma Singleton
    import QtQuick

    // GENERATED by qml/stargate/generate.nix from the active theme + fonts presets.
    // Do not edit by hand.
    QtObject {
        // ---- Catppuccin ${theme.flavor} palette ----
    ${paletteProps}

        // ---- Semantic aliases ----
        readonly property color bg:       crust     // screen background
        readonly property color panel:    mantle    // bar, cards, segmented controls
        readonly property color border:   surface0  // panel outlines, dividers
        readonly property color hairline: base      // list row separators
        readonly property color fg:       text
        readonly property color dim:      overlay0  // secondary labels
        readonly property color label:    overlay1  // section kickers
        readonly property color onAccent: crust     // text on a filled accent

        // A chevron that has not engaged. Between base and surface0, dark enough
        // that an unlit chevron reads as off rather than merely dimmer.
        readonly property color unlit: "#2a2b3d"

        // ---- Typography (from the active fonts preset) ----
        readonly property string fontUi:   "${fonts.sansSerif.exact-name}"
        readonly property string fontMono: "${fonts.mono.exact-name}"

        // ---- Localisation ----
        // Named explicitly: the greeter runs as the `sddm` user and inherits neither
        // the host's LANG nor its LC_TIME, and the lock formats the same way so the
        // two screens never disagree about the date.
        readonly property string locale: "${style.locale}"

        // ---- Metrics ----
        // Every screen is authored in a 1080px-tall design space and scaled to the
        // monitor's real height, so these are design pixels.
        readonly property int designHeight: 1080
        readonly property int barHeight:    52
        readonly property int barMargin:    18
        readonly property int barRadius:    16
    }
  '';

  configQml = ''
    pragma Singleton
    import QtQuick

    // GENERATED by qml/stargate/generate.nix from the stargate style preset.
    // Do not edit by hand.
    QtObject {
        // Connector name -> screen role. The greeter gets one QML engine per monitor
        // and the lock one surface per monitor; both read this to decide which of the
        // three screens they are drawing.
        readonly property var screens: ${scalarObject style.screens}

        // Theme palette *names*, resolved as Theme[name] at the use site so a theme
        // flavor change follows without regenerating this file.
        readonly property var colors: ${scalarObject style.colors}

        // Gate geometry and dialling behaviour. maxPreLock bounds how many chevrons
        // typing may light before Enter, and therefore how much of the password's
        // length the screen reveals.
        readonly property var gate: ${scalarObject style.gate}

        // Dial-home device: two rings of `keys`, reshuffling its lit set every
        // `shimmerMs`.
        readonly property var dhd: ${scalarObject style.dhd}

        // Lock-screen specifics; the greeter ignores these.
        readonly property var lock: ${scalarObject style.lock}

        readonly property bool clock24: ${lib.boolToString style.clock24}

        // Chrome glyphs, as Nerd Font codepoints.
        readonly property var icons: ${glyphObject style.icons}

        // Session name (lowercased) -> glyph for the greeter's "Destination" picker.
        readonly property var sessionIcons: ${glyphObject style.sessionIcons}
    }
  '';
}
