import QtQuick
import Quickshell
import Quickshell.Wayland
// Brings the config-root module (Theme.qml singleton, generated by home.nix) into scope.
import "root:/"

// Step 1 baseline: a floating top bar on every monitor with a centered clock pill.
// Colors + fonts come from the Theme singleton, which is generated from the repo's
// active theme + fonts presets. Later stages replace this inline bar with real
// components (workspaces, system module, etc.) split into their own QML files.
ShellRoot {
    Variants {
        // One PanelWindow per connected screen — mirrors the 3-monitor desktop layout.
        model: Quickshell.screens

        PanelWindow {
            required property var modelData
            screen: modelData

            anchors {
                top: true
                left: true
                right: true
            }

            implicitHeight: Theme.barHeight
            color: "transparent"

            // Centered "mantle island" clock pill.
            Rectangle {
                anchors.centerIn: parent
                implicitWidth: clockText.implicitWidth + 28
                implicitHeight: 26
                radius: height / 2
                color: Theme.surface

                Text {
                    id: clockText
                    anchors.centerIn: parent
                    color: Theme.fg
                    font.family: Theme.fontMono
                    font.pixelSize: 13
                    text: Qt.formatDateTime(new Date(), "ddd dd MMM  HH:mm")

                    // Tick every second; format shows to the minute.
                    Timer {
                        interval: 1000
                        running: true
                        repeat: true
                        onTriggered: clockText.text =
                            Qt.formatDateTime(new Date(), "ddd dd MMM  HH:mm")
                    }
                }
            }
        }
    }
}
